---

root: true

env:
  commonjs: true
  es6: true

extends:
  - eslint:recommended
  - prettier

rules:

  ## Possible Errors

  for-direction: error
  no-prototype-builtins: error
  no-template-curly-in-string: error

  ## Best Practices

  array-callback-return: error
  block-scoped-var: error
  complexity:
    - error
    - 16
  consistent-return: error
  curly: error
  default-case: error
  dot-notation: error
  eqeqeq: error
  guard-for-in: error
  no-alert: error
  no-caller: error
  no-div-regex: error
  no-empty-function: error
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-global-assign: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal-escape: error
  no-proto: error
  no-return-assign: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-return: error
  no-void: error
  no-with: error
  prefer-promise-reject-errors: error
  radix: error
  yoda: error

  ## Strict Mode

  strict: error

  ## Variables

  no-catch-shadow: error
  no-label-var: error
  no-shadow: error
  no-shadow-restricted-names: error
  no-undef-init: error
  no-undefined: error
  no-use-before-define: error

  ## Node.js and CommonJS

  callback-return: error
  handle-callback-err: error
  no-buffer-constructor: error
  no-mixed-requires: error
  no-new-require: error
  no-path-concat: error
  no-process-env: error
  no-process-exit: error

  ## Stylistic Issues

  camelcase: error
  capitalized-comments:
    - error
    - always
    - ignoreConsecutiveComments: true
  consistent-this: error
  func-name-matching: error
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  id-match: error
  linebreak-style:
    - error
    - unix
  lines-between-class-members: error
  max-depth: error
  max-nested-callbacks:
    - error
    - max: 6
  max-statements-per-line: error
  new-cap: error
  no-array-constructor: error
  no-bitwise: error
  no-continue: error
  no-lonely-if: error
  no-multi-assign: error
  no-negated-condition: error
  no-nested-ternary: error
  no-new-object: error
  no-underscore-dangle:
    - error
    - allowAfterThis: true
  no-unneeded-ternary: error
  one-var:
    - error
    - never
  operator-assignment: error
  padding-line-between-statements: error
  sort-vars: error
  spaced-comment: error

  ## ECMAScript 6

  arrow-body-style: error
  no-duplicate-imports: error
  no-restricted-imports: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: error
  prefer-numeric-literals: error
  prefer-spread: error
  prefer-template: error
  sort-imports: error
  symbol-description: error
