---

language: node_js

node_js:
- 10 # EOL: April 2021
- 9 # EOL: June 2018
- 8 # EOL: December 2019
- 6 # EOL: April 2019

script:
- npm run test-mocha
- npm run test-readme
- npm run lint

after_script:
- npm run coveralls

notifications:
  email:
    on_success: never
    on_failure: always

# Identifies `a.b.c-xxx.n` tags as pre-releases, and `a.b.c` as stable releases
before_deploy: |
  function npm_dist_tag() {
    if [[ "$TRAVIS_TAG" = *"-"* ]]; then
      echo "next"
    else
      echo "latest"
    fi
  }

deploy:
  provider: npm
  tag: $(npm_dist_tag)
  email:
    secure: bXNlycnAR6z+PawxKBB6fSKuoAQb61bH3gYhOD8yIP5Lx0zj6HHDj8Ze4jsE8X133RVVWUPONqw0D09b/w0ahWfRlY80/TzOlT6HgYHTLKuKZsgGrLDbSBBGeXzU4I+/Zuo3fJ7xGIUIRe4qrUELnUYNE7VuB1Un78xTmkuZ0cY=
  api_key:
    secure: Gjd/+7HvWJhVopSDHGirlMjk872jDK+/pW/s1cE5pHFz5Zfbn4wpAuoncQ8oLNwnndPkAMwBzNvwpOfQiCrccIuERY6f73Jtmd+dzGCgf7WRFB1Jz0ih06Xu/CSNN/nApaMMoj++/s/m6lu+NLNOgQ7aYZEEwJyfi3T7ik0AcJ4=
  on:
    node: 8
    tags: true
    repo: astorije/chai-immutable

# If the current release is a stable release, remove potential pre-release tag
after_deploy: |
  if [ "$(npm_dist_tag)" == "latest" ]; then
    npm dist-tag rm thelounge next || true
  fi
