language: node_js

# https://github.com/nodejs/Release
node_js:
  - 12 # EOL: 2022-04-01
  - 10 # EOL: 2021-04-01
  - 8 # EOL: 2019-12-31

os:
  - linux
  - osx

matrix:
  include:
    - env: IMMUTABLE_VERSION=^4.0.0-rc

install:
  - yarn install --frozen-lockfile

before_script:
  - if [ "$IMMUTABLE_VERSION" ]; then yarn add --dev immutable@$IMMUTABLE_VERSION; fi

after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_NODE_VERSION" == "12" ]]; then yarn coveralls; fi

notifications:
  email:
    on_success: never
    on_failure: always

# Identifies `a.b.c-xxx.n` tags as pre-releases, and `a.b.c` as stable releases
before_deploy: |
  function dist_tag() {
    if [[ "$TRAVIS_TAG" = *"-"* ]]; then
      echo "next"
    else
      echo "latest"
    fi
  }

deploy:
  provider: npm
  tag: $(dist_tag)
  email:
    secure: bXNlycnAR6z+PawxKBB6fSKuoAQb61bH3gYhOD8yIP5Lx0zj6HHDj8Ze4jsE8X133RVVWUPONqw0D09b/w0ahWfRlY80/TzOlT6HgYHTLKuKZsgGrLDbSBBGeXzU4I+/Zuo3fJ7xGIUIRe4qrUELnUYNE7VuB1Un78xTmkuZ0cY=
  api_key:
    secure: lmkAwQspZnROe6Ev0QdV/9l1cN10BWMyc7BfkecNVr1Ab1G6Kws4LoczbJS/VJmLmvKaSMppLvmA+32pIu1XGa3ezjQQoobi1VPTH7RUGOY57y3japctsgI9JFXzFIESJo6lspe8blSHH7J6pyEJ0Vbl6gnDju9ploQWCawdh1g=
  on:
    node: 10
    os: linux
    tags: true
    repo: astorije/chai-immutable

# If the current release is a stable release, remove potential pre-release tag
after_deploy: |
  if [ "$(dist_tag)" == "latest" ]; then
    npm dist-tag rm chai-immutable next || true
  fi
