language: node_js
node_js:
- '0.12'
- '0.10'
after_script:
- npm run coveralls
deploy:
  provider: npm
  email: jeremie@astori.fr
  api_key:
    secure: Gjd/+7HvWJhVopSDHGirlMjk872jDK+/pW/s1cE5pHFz5Zfbn4wpAuoncQ8oLNwnndPkAMwBzNvwpOfQiCrccIuERY6f73Jtmd+dzGCgf7WRFB1Jz0ih06Xu/CSNN/nApaMMoj++/s/m6lu+NLNOgQ7aYZEEwJyfi3T7ik0AcJ4=
  on:
    node: '0.12'
    tags: true
    repo: astorije/chai-immutable
