---

language: node_js

node_js:
- 9 # Current stable
- 8 # Active LTS until April 2019
- 6 # Active LTS until April 2018
- 4 # Maintenance LTS until 2018-04-01

script:
- npm run test-mocha
- npm run test-readme
- npm run lint

after_script:
- npm run coveralls

notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  provider: npm
  email: jeremie@astori.fr
  api_key:
    secure: Gjd/+7HvWJhVopSDHGirlMjk872jDK+/pW/s1cE5pHFz5Zfbn4wpAuoncQ8oLNwnndPkAMwBzNvwpOfQiCrccIuERY6f73Jtmd+dzGCgf7WRFB1Jz0ih06Xu/CSNN/nApaMMoj++/s/m6lu+NLNOgQ7aYZEEwJyfi3T7ik0AcJ4=
  on:
    node: 4
    tags: true
    repo: astorije/chai-immutable
