# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: '{build}'

# Do not build on tags (GitHub only)
skip_tags: true

environment:
  matrix:
    - nodejs_version: 10 # EOL: April 2021
    - nodejs_version: 8 # EOL: December 2019
    - nodejs_version: 6 # EOL: April 2019

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install --frozen-lockfile
  - yarn add --dev mocha-appveyor-reporter
  - echo --reporter mocha-appveyor-reporter >> test/mocha.opts

test_script:
  - node --version
  - yarn --version
  - yarn test

# cache npm modules
cache:
  - "%LOCALAPPDATA%\\Yarn"

# Don't actually build
build: off
