---
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

# Do not build on tags (GitHub only)
skip_tags: true

environment:
  matrix:
  - nodejs_version: 10 # EOL: April 2021
  - nodejs_version: 9 # EOL: June 2018
  - nodejs_version: 8 # EOL: December 2019
  - nodejs_version: 6 # EOL: April 2019

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install mocha-appveyor-reporter
  - echo --reporter mocha-appveyor-reporter >> test/mocha.opts

test_script:
  - node --version
  - npm --version
  - npm run test-mocha
  - npm run test-readme
  - npm run lint

# Don't actually build
build: off
