---
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

# Do not build on tags (GitHub only)
skip_tags: true

environment:
  matrix:
  - nodejs_version: 9 # Current stable
  - nodejs_version: 8 # Active LTS until April 2019
  - nodejs_version: 6 # Active LTS until April 2018
  - nodejs_version: 4 # Maintenance LTS until 2018-04-01

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install mocha-appveyor-reporter
  - echo --reporter mocha-appveyor-reporter >> test/mocha.opts

test_script:
  - node --version
  - npm --version
  - npm run test-mocha
  - npm run test-phantomjs
  - npm run test-readme
  - npm run check-style

# Don't actually build
build: off
